receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "localhost:4317"
      http:
        endpoint: "localhost:4318"

exporters:
  otlp/traces:
    endpoint: https://your-otlp-endpoint.com
    headers:
      your-api-key-header: <your-api-key>

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/traces]
  telemetry:
    metrics:
      address: localhost:8888
