#
# Build the collector config layer with the appropriate config for each type of function
#
build-CollectorConfiglLayer:
	@echo "Copying collector.yaml to artifacts directory"
	@cp -r otel adot rotel "$(ARTIFACTS_DIR)"/

