AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: AWS SAM template for the serverless-otlp-forwarder application.


Globals:
  Function:
    MemorySize: 128
    Timeout: 3
    Architectures:
      - arm64
    Runtime: provided.al2023
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
      ApplicationLogLevel: INFO
      SystemLogLevel: INFO
  

Resources:
  HandlerExample:
    # instrumented with create_traced_handler
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
      BuildProperties:
        Binary: handler-example
    Properties:
      FunctionName: !Sub '${AWS::StackName}-lambda-handler-example'
      CodeUri: ./
      Handler: bootstrap
      Description: 'Demo Handler Example Lambda function to showcase OpenTelemetry integration'
      FunctionUrlConfig:
        AuthType: NONE
      Environment:
        Variables:
          LAMBDA_EXTENSION_SPAN_PROCESSOR_MODE: async

  TowerExample:
    # instrumented with the Tower layer
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
      BuildProperties:
        Binary: tower-example
    Properties:
      FunctionName: !Sub '${AWS::StackName}-lambda-tower-example'
      CodeUri: ./
      Handler: bootstrap
      Runtime: provided.al2023
      Description: 'Demo Tower Example Lambda function to showcase OpenTelemetry integration'
      FunctionUrlConfig:
        AuthType: NONE
      Environment:
        Variables:
          LAMBDA_EXTENSION_SPAN_PROCESSOR_MODE: async

Outputs:
  HandlerExampleFunctionUrl:
    Description: 'URL of the Demo Handler Example Lambda function'
    Value: !GetAtt HandlerExampleUrl.FunctionUrl
  TowerExampleFunctionUrl:
    Description: 'URL of the Demo Tower Example Lambda function'
    Value: !GetAtt TowerExampleUrl.FunctionUrl
