version = 0.1
[default.global.parameters]
beta_features = "yes"
stack_name = "lambda-otel-lite-node"

[default.build.parameters]
build_in_source = true

[default.deploy.parameters]
resolve_s3 = true
s3_prefix = "lambda-otel-lite-node"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
