# .github/workflows/pr-check-startled.yml
name: PR Checks for startled CLI

on:
  pull_request:
    paths:
      - 'cli/startled/**'
    types: [opened, synchronize, reopened, ready_for_review]

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: "1.85" 

jobs:
  check_startled:
    name: Check startled on ${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os_name: ubuntu-24.04
            arch: amd64
            rust_target: x86_64-unknown-linux-gnu
          - os_name: ubuntu-24.04-arm
            arch: arm64
            rust_target: aarch64-unknown-linux-gnu
    runs-on: ${{ matrix.os_name }}
    defaults:
      run:
        working-directory: cli/startled
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: rustfmt, clippy
          # target: ${{ matrix.rust_target }} # Not strictly needed for host checks

      - name: Set up Rust cache for startled (${{ matrix.arch }})
        uses: Swatinem/rust-cache@v2
        with:
          key: pr-startled-${{ matrix.arch }}-${{ runner.os }}-${{ hashFiles('cli/startled/Cargo.lock') }}

      - name: Run quality checks for startled (${{ matrix.arch }})
        run: |
          cargo fmt --check
          cargo clippy --all-targets -- -D warnings # --all-targets for platform-specific lints
          cargo test --all-features # This will include default features like 'screenshots'

      - name: Attempt to build startled (${{ matrix.arch }})
        run: cargo build --all-features # This will include default features like 'screenshots'
